import = [
    # "~/.config/alacritty/catppuccin-latte.toml"
    "~/.config/alacritty/catppuccin-frappe.toml"
    # "~/.config/alacritty/catppuccin-macchiato.toml"
    # "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 13.0

[font.bold]
family = "MesloLGM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGM Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGM Nerd Font"
style = "Regular"

[window]
opacity = 0.795
